ccflags-y += -Idrivers/media/platform/camera_v2-legacy
ccflags-y += -Idrivers/media/platform/camera_v2-legacy/common
ccflags-y += -Idrivers/media/platform/camera_v2-legacy/sensor/io
ccflags-y += -Idrivers/media/platform/camera_v2-legacy/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
