ccflags-y += -Idrivers/media/platform/camera_v2-legacy
ccflags-y += -Idrivers/media/platform/camera_v2-legacy/common
ccflags-y += -Idrivers/media/platform/camera_v2-legacy/sensor/io
obj-$(CONFIG_MSM_CSIPHY) += msm_csiphy.o
