ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/sensor

obj-$(CONFIG_MEIZU_HW) += meizu_hw.o
